apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: l7ajbdjz8-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:b84cc6dc28b86e8cd3e872ae6ea5a5df1939edc5@sha256:f97937582a57250f409e9fcd14cf1466dbffae4a7c2a5982a61f017b4f4bf23c
          name: container-image
